[C++20] Fix compile error caused by ambiguous == operator
Flip the order or the two objects

error: use of overloaded operator '==' is ambiguous (with operand types 'const StoredDocKeyT<std::allocator>' and 'const SerialisedDocKey')
  if (lhs == rhs) {
      ~~~ ^  ~~~

Change-Id: Iedd0354b75e35e07dee351cfe54cfe2296044ff0
Reviewed-on: https://review.couchbase.org/c/kv_engine/+/208460
Tested-by: Build Bot <build@couchbase.com>
Reviewed-by: Jim Walker <jim@couchbase.com>