ASan: Add missing add_sanitizers() to test executables
Various test executables links against libraries which enable
AddressSanitizer - as such we need to enable ASan on the target itself
to avoid linker errors when building with CB_ADDRESSSANITIZER=2
(i.e. explicit target linking). For example:

    [ 65%] Linking CXX executable ../../tracing_bench
    /usr/bin/ld: ../../libmcd_tracing.a(tracer.cc.o): undefined reference to symbol '__asan_report_store4'
    //usr/local/lib64/libasan.so.4: error adding symbols: DSO missing from command line
    collect2: error: ld returned 1 exit status

Change-Id: Ia4257bb664ae2472e3c8f5de8af0b48c5463289e
Reviewed-on: http://review.couchbase.org/101541
Tested-by: Build Bot <build@couchbase.com>
Reviewed-by: Daniel Owen <owend@couchbase.com>