Revert "MB-37944: Replace cb::const_char_buffer with std::string_view"
This is causing a build break:

[ 80%] Linking CXX executable ../../../ep-engine_ep_unit_tests
../CMakeFiles/ep_objs.dir/src/dcp/consumer.cc.o: In function `DcpConsumer::addStats(std::function<void (std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, gsl::not_null<void const*>)> const&, void const*)':
<http://server.jenkins.couchbase.com/job/couchbase-server-unix/ws/kv_engine/engines/ep/src/dcp/consumer.cc>:1102: undefined reference to `void ConnHandler::addStat<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, gsl::not_null<void const*>)> const&, void const*) const'
collect2: error: ld returned 1 exit status

This reverts commit bae93daf0458540dda26a93b2e7c08139768dff8.

Change-Id: I4171303be3c59777c689fbc21f4f937ca6877b04
Reviewed-on: http://review.couchbase.org/123893
Reviewed-by: Trond Norbye <trond.norbye@couchbase.com>
Tested-by: Trond Norbye <trond.norbye@couchbase.com>