MB-17508 2/4 Expose detailed range errors to SET_PARAM requests
Exposes detailed validation error messages from the configuration validators
further down the stack out on the body of the response instead of a generic
'out of range' style message.

The primary purpose of this is to expose error reasons when using epctl.
Sample output:

> $ ./cbepctl localhost:12001 set flush_param exp_pager_initial_run_time 25
> setting param: exp_pager_initial_run_time 25
> Error: Validation Error, exp_pager_initial_run_time takes values between -1 and 23 (Got: 25)

Change-Id: Ib19c0056d1f289b43c84185a33efa27d20d8ce24
Reviewed-on: http://review.couchbase.org/58937
Reviewed-by: Dave Rigby <daver@couchbase.com>
Tested-by: buildbot <build@couchbase.com>
Reviewed-by: Chiyoung Seo <chiyoung@couchbase.com>