MB-61385: Handle invalid CAS values
Previously, we would accept any CAS value when executing set/del
with meta operations. A faulty input could "poison" the max_cas
of the vbucket, affecting the HLC and, ultimately, LWW conflict
resolution via XDCR.

This patch introduces a config parameter: hlc_invalid_strategy.
This determines how set/del with meta operations handle invalid
CAS values. They are three possible values,
error: fails any CAS value outside hlc_max_future_threshold,
ignore: ignores CAS validation (previous behaviour).
replace: generates a new CAS for invalid values.

Change-Id: I26a30b0c08c173b867a4d1a822e299bd4b66cfb8
Reviewed-on: https://review.couchbase.org/c/kv_engine/+/208810
Tested-by: Build Bot <build@couchbase.com>
Reviewed-by: Vesko Karaganev <vesko.karaganev@couchbase.com>