Revert "Fix data race in CouchKVStore stats access"
(as this breaks windows:
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\vector(1708) : error C2558: class 'Couchbase::RelaxedAtomic<uint64_t>' : no copy constructor available or copy constructor is declared 'explicit')

This reverts commit a847eb3aa610956ba738098d45767c012ed8bdfb.

Change-Id: I05c57a1be697c50f4ae091e277c684bc2f8afdd5
Reviewed-on: http://review.couchbase.org/55887
Reviewed-by: abhinav dangeti <abhinav@couchbase.com>
Tested-by: abhinav dangeti <abhinav@couchbase.com>