MB-9640: Add missing <limits>
The build slave failed with:
src/generated_configuration.cc: In member function ‘void Configuration::initialize()’:
src/generated_configuration.cc:466:42: error: ‘numeric_limits’ is not a member of ‘std’
src/generated_configuration.cc:466:68: error: expected primary-expression before ‘>’ token
src/generated_configuration.cc:466:69: error: ‘::max’ has not been declared
src/generated_configuration.cc:466:69: note: suggested alternative:

src/generated_configuration.cc:467:41: error: ‘numeric_limits’ is not a member of ‘std’
src/generated_configuration.cc:467:67: error: expected primary-expression before ‘>’ token
src/generated_configuration.cc:467:68: error: ‘::max’ has not been declared
src/generated_configuration.cc:467:68: note: suggested alternative:
/usr/include/c++/4.6/bits/stl_algobase.h:254:5: note:   ‘std::max’

It's fixed with including <limits>.

Change-Id: If5d74f0b5d9e575f46f49d4ad75d4179aa62b35d
Reviewed-on: http://review.couchbase.org/30625
Reviewed-by: Trond Norbye <trond.norbye@gmail.com>
Tested-by: Trond Norbye <trond.norbye@gmail.com>