Add a constructor from a nullptr_t to TaggedPtr
Otherwise I get the following compilation errors on gcc 10.2.0.

In file included from /usr/include/c++/10.2.0/memory:83,
                 from .../repo-master/kv_engine/engines/ep/src/atomic.h:23,
                 from .../repo-master/kv_engine/engines/ep/src/globaltask.h:20,
                 from .../repo-master/kv_engine/engines/ep/src/access_scanner.h:19,
                 from .../repo-master/kv_engine/engines/ep/src/access_scanner.cc:18:
/usr/include/c++/10.2.0/bits/unique_ptr.h: In instantiation of ‘std::__uniq_ptr_impl<_Tp, _Dp>::__uniq_ptr_impl(std::__uniq_ptr_impl<_Tp, _Dp>&&) [with _Tp = StoredValue; _Dp = TaggedPtrDeleter<StoredValue, StoredValue::Deleter>]’:
/usr/include/c++/10.2.0/bits/unique_ptr.h:211:7:   required from here
/usr/include/c++/10.2.0/bits/unique_ptr.h:163:22: no match for ‘operator=’ (operand types are ‘std::__uniq_ptr_impl<StoredValue, TaggedPtrDeleter<StoredValue, StoredValue::Deleter> >::pointer’ {aka ‘TaggedPtr<StoredValue>’} and ‘std::nullptr_t’)
  163 |       { __u._M_ptr() = nullptr; }
      |         ~~~~~~~~~~~~~^~~~~~~~~
In file included from .../repo-master/kv_engine/engines/ep/src/blob.h:21,
                 from .../repo-master/kv_engine/engines/ep/src/stored-value.h:20,
                 from .../repo-master/kv_engine/engines/ep/src/hash_table.h:21,
                 from .../repo-master/kv_engine/engines/ep/src/access_scanner.cc:22:
.../repo-master/kv_engine/engines/ep/src/tagged_ptr.h:44:7: note: candidate: ‘constexpr TaggedPtr<StoredValue>& TaggedPtr<StoredValue>::operator=(const TaggedPtr<StoredValue>&)’
   44 | class TaggedPtr : public TaggedPtrBase {
      |       ^~~~~~~~~
.../repo-master/kv_engine/engines/ep/src/tagged_ptr.h:44:7: note:   no known conversion for argument 1 from ‘std::nullptr_t’ to ‘const TaggedPtr<StoredValue>&’
.../repo-master/kv_engine/engines/ep/src/tagged_ptr.h:44:7: note: candidate: ‘constexpr TaggedPtr<StoredValue>& TaggedPtr<StoredValue>::operator=(TaggedPtr<StoredValue>&&)’
.../repo-master/kv_engine/engines/ep/src/tagged_ptr.h:44:7: note:   no known conversion for argument 1 from ‘std::nullptr_t’ to ‘TaggedPtr<StoredValue>&&’
In file included from /usr/include/c++/10.2.0/memory:83,
                 from .../repo-master/kv_engine/engines/ep/src/atomic.h:23,
                 from .../repo-master/kv_engine/engines/ep/src/globaltask.h:20,
                 from .../repo-master/kv_engine/engines/ep/src/access_scanner.h:19,
                 from .../repo-master/kv_engine/engines/ep/src/access_scanner.cc:18:
/usr/include/c++/10.2.0/bits/unique_ptr.h: In instantiation of ‘std::__uniq_ptr_impl<_Tp, _Dp>::pointer std::__uniq_ptr_impl<_Tp, _Dp>::release() [with _Tp = StoredValue; _Dp = TaggedPtrDeleter<StoredValue, StoredValue::Deleter>; std::__uniq_ptr_impl<_Tp, _Dp>::pointer = TaggedPtr<StoredValue>]’:
/usr/include/c++/10.2.0/bits/unique_ptr.h:167:12:   required from ‘std::__uniq_ptr_impl<_Tp, _Dp>& std::__uniq_ptr_impl<_Tp, _Dp>::operator=(std::__uniq_ptr_impl<_Tp, _Dp>&&) [with _Tp = StoredValue; _Dp = TaggedPtrDeleter<StoredValue, StoredValue::Deleter>]’
/usr/include/c++/10.2.0/bits/unique_ptr.h:212:24:   required from here
/usr/include/c++/10.2.0/bits/unique_ptr.h:188:11: no match for ‘operator=’ (operand types are ‘std::__uniq_ptr_impl<StoredValue, TaggedPtrDeleter<StoredValue, StoredValue::Deleter> >::pointer’ {aka ‘TaggedPtr<StoredValue>’} and ‘std::nullptr_t’)
  188 |  _M_ptr() = nullptr;
      |  ~~~~~~~~~^~~~~~~~~
In file included from .../repo-master/kv_engine/engines/ep/src/blob.h:21,
                 from .../repo-master/kv_engine/engines/ep/src/stored-value.h:20,
                 from .../repo-master/kv_engine/engines/ep/src/hash_table.h:21,
                 from .../repo-master/kv_engine/engines/ep/src/access_scanner.cc:22:
.../repo-master/kv_engine/engines/ep/src/tagged_ptr.h:44:7: note: candidate: ‘constexpr TaggedPtr<StoredValue>& TaggedPtr<StoredValue>::operator=(const TaggedPtr<StoredValue>&)’
   44 | class TaggedPtr : public TaggedPtrBase {
      |       ^~~~~~~~~
.../repo-master/kv_engine/engines/ep/src/tagged_ptr.h:44:7: note:   no known conversion for argument 1 from ‘std::nullptr_t’ to ‘const TaggedPtr<StoredValue>&’
.../repo-master/kv_engine/engines/ep/src/tagged_ptr.h:44:7: note: candidate: ‘constexpr TaggedPtr<StoredValue>& TaggedPtr<StoredValue>::operator=(TaggedPtr<StoredValue>&&)’
.../repo-master/kv_engine/engines/ep/src/tagged_ptr.h:44:7: note:   no known conversion for argument 1 from ‘std::nullptr_t’ to ‘TaggedPtr<StoredValue>&&’
make[4]: *** [kv_engine/engines/ep/CMakeFiles/ep_objs.dir/build.make:134: kv_engine/engines/ep/CMakeFiles/ep_objs.dir/src/access_scanner.cc.o] Error 1

(Also add a missing include of <cstdint> which is required with with
GCC 10.)

Change-Id: I27e5492480661ccdba57d7bee5dcd24f8c0ce463
Reviewed-on: http://review.couchbase.org/c/kv_engine/+/142940
Reviewed-by: James Harrison <james.harrison@couchbase.com>
Tested-by: Dave Rigby <daver@couchbase.com>