Add dependency to generated source from mcd_executor
[2/3] Building CXX object kv_engine/executor/CMakeFiles/mcd_executor.dir/Unity/unity_0_cxx.cxx.o
FAILED: kv_engine/executor/CMakeFiles/mcd_executor.dir/Unity/unity_0_cxx.cxx.o
/usr/bin/ccache /usr/bin/c++ -DCB_DEVELOPMENT_ASSERTS -DCOUCHBASE_ENTERPRISE_EDITION=1 -DDESTINATION_ROOT=\"/home/trond/compile/trunk/cmake-install-debug\" -DFMT_LOCALE -DGLOG_NO_ABBREVIATED_SEVERITIES -DGOOGLE_GLOG_DLL_DECL="" -DHAVE_BREAKPAD -DHAVE_JEMALLOC -DHAVE_JEMALLOC_SDALLOCX -DHAVE_LIBNUMA=1 -DJETBRAINS_CLION_IDE -DJSON_USE_IMPLICIT_CONVERSIONS=1 -DMEMCACHED_VERSION=\"a15c21b2105de1322a584218a0526d0006c4d67d\" -DOBJECT_ROOT=\"/home/trond/compile/trunk/cmake-build-debug/kv_engine\" -DPRODUCT_VERSION=\"7.2.0-0000\" -DSOURCE_ROOT=\"/home/trond/compile/trunk/kv_engine\" -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS -D__EXTENSIONS__=1 -D__STDC_FORMAT_MACROS -Dgsl_CONFIG_CONTRACT_VIOLATION_THROWS -I/home/trond/compile/trunk/cmake-build-debug/kv_engine/include -I/home/trond/compile/trunk/kv_engine -I/home/trond/compile/trunk/kv_engine/include -I/home/trond/compile/trunk/cmake-build-debug/platform/include -I/home/trond/compile/trunk/cmake-build-debug/tlm/deps/googletest.exploded/include -I/home/trond/compile/trunk/platform/include -I/home/trond/compile/trunk/cmake-build-debug/kv_engine/engines/ep/src -I/home/trond/compile/trunk/cmake-build-debug/kv_engine/statistics/src -isystem /home/trond/compile/trunk/phosphor/include -isystem /home/trond/compile/trunk/third_party/gsl-lite/include -isystem /home/trond/compile/trunk/cmake-build-debug/tlm/deps/libevent.exploded/include -isystem /home/trond/compile/trunk/cmake-build-debug/tlm/deps/openssl.exploded/include -isystem /home/trond/compile/trunk/cmake-build-debug/tlm/deps/boost.exploded/include -isystem /home/trond/compile/trunk/cmake-build-debug/tlm/deps/jemalloc.exploded/include -isystem /home/trond/compile/trunk/cmake-build-debug/tlm/deps/folly.exploded/include -isystem /home/trond/compile/trunk/cmake-build-debug/tlm/deps/double-conversion.exploded/include -isystem /home/trond/compile/trunk/cmake-build-debug/tlm/deps/glog.exploded/include -isystem /home/trond/compile/trunk/cmake-build-debug/tlm/deps/json.exploded/include -isystem /home/trond/compile/trunk/third_party/HdrHistogram_c/src -isystem /home/trond/compile/trunk/cmake-build-debug/tlm/deps/spdlog.exploded/include -isystem /home/trond/compile/trunk/cmake-build-debug/tlm/deps/fmt.exploded/include -isystem /home/trond/compile/trunk/cmake-build-debug/tlm/deps/prometheus-cpp.exploded/include -fvisibility=hidden -pthread -pedantic -Wall -Wredundant-decls -Werror=missing-braces -fno-strict-aliasing -Werror=switch -g -std=c++17 -Winvalid-pch -include /home/trond/compile/trunk/cmake-build-debug/kv_engine/CMakeFiles/kv_pch.dir/cmake_pch.hxx -MD -MT kv_engine/executor/CMakeFiles/mcd_executor.dir/Unity/unity_0_cxx.cxx.o -MF kv_engine/executor/CMakeFiles/mcd_executor.dir/Unity/unity_0_cxx.cxx.o.d -o kv_engine/executor/CMakeFiles/mcd_executor.dir/Unity/unity_0_cxx.cxx.o -c /home/trond/compile/trunk/cmake-build-debug/kv_engine/executor/CMakeFiles/mcd_executor.dir/Unity/unity_0_cxx.cxx
In file included from /home/trond/compile/trunk/kv_engine/engines/ep/src/ep_engine.h:14,
                 from /home/trond/compile/trunk/kv_engine/executor/cb3_executorpool.cc:16,
                 from /home/trond/compile/trunk/cmake-build-debug/kv_engine/executor/CMakeFiles/mcd_executor.dir/Unity/unity_0_cxx.cxx:5:
/home/trond/compile/trunk/kv_engine/engines/ep/src/configuration.h:185:10: fatal error: generated_configuration.h: No such file or directory
  185 | #include "generated_configuration.h" // NOLINT(*)
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Change-Id: I143526e3a0dc49410669e165aaf76e1648119dee
Reviewed-on: https://review.couchbase.org/c/kv_engine/+/174306
Reviewed-by: Jim Walker <jim@couchbase.com>
Tested-by: Trond Norbye <trond.norbye@couchbase.com>