Allow tasks.def.h to be included by clang-tidy
When clang-tidy tries to check the file as part of CV it treats
the file as a standalone unit and fails with:

    error: C++ requires a type specifier for all declarations
           [clang-diagnostic-error]
    TASK(MultiBGFetcherTask, READER_TASK_IDX, 0)
    ^

This happens because the TASK hasn't been defined yet. To
work around this problem this patch defines TASK with the
expected number of parameters.

Change-Id: I7f78aeefee916919d67382814dbe930623a3a53e
Reviewed-on: http://review.couchbase.org/c/kv_engine/+/155998
Tested-by: Trond Norbye <trond.norbye@couchbase.com>
Reviewed-by: Dave Rigby <daver@couchbase.com>