Fixes for ASan upgrade to clang 9
Fix a few issues seen when using clang 9 for ASan+UBsan build:

* Missing mock_dcp objects in ep_engine_benchmark (addressses
  "undefined reference to `typeinfo for MockDcpMessageProducers'"
  error).

* Correctly set const on deleted RangeIterator copy ctor.

* Skip HdrHistogramTest.int64MaxSizeTest under UBSan.

Change-Id: I93cac6c4b44a5a90e3bf4f098fccfb4ac08dbe67
Reviewed-on: http://review.couchbase.org/c/kv_engine/+/135996
Reviewed-by: Trond Norbye <trond.norbye@couchbase.com>
Tested-by: Build Bot <build@couchbase.com>