Move definition of CacheLocalStatistics to header (C++20)
Caused compile error on MacOS with clang 15 with C++20:

error: arithmetic on a pointer to an incomplete type 'HashTable::Statistics::CacheLocalStatistics'
        __alloc_traits::destroy(__alloc(), std::__to_address(--__soon_to_be_end));

Change-Id: Ice24cb2949ff62c7f19ef7c40d93d08b77725954
Reviewed-on: https://review.couchbase.org/c/kv_engine/+/208459
Reviewed-by: Jim Walker <jim@couchbase.com>
Tested-by: Build Bot <build@couchbase.com>