Revert "MB-14189: Create stubs for ForestKVStore"
Reverting as it currently breaks Windows build - see http://factory.couchbase.com/job/tlm-gerrit-master/36/label_exp=sherlocker-windows/console

    src\kvstore.cc(56) : error C2065: 'S_IRWXU' : undeclared identifier
    src\kvstore.cc(56) : error C3861: 'mkdir': identifier not found

This reverts commit feafd3c1107d6c04c5e51a05d502712b33a875e5.

Change-Id: Ie6dc6caeb336c8bf475fc668a648f5891d569029
Reviewed-on: http://review.couchbase.org/49385
Reviewed-by: Sriram Ganesan <sriram@couchbase.com>
Tested-by: buildbot <build@couchbase.com>